# Generated by Django 3.2.12 on 2023-03-18 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('coverimg', models.CharField(max_length=1000)),
                ('img1', models.CharField(max_length=1000)),
                ('img2', models.CharField(max_length=1000)),
                ('img3', models.CharField(max_length=1000)),
                ('descrition', models.TextField()),
                ('aim', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
