# Generated by Django 3.2.12 on 2023-03-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='descrition',
            new_name='description',
        ),
    ]
