# Generated by Django 3.2.12 on 2023-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_descrition_ngo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='coverimg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
