# Generated by Django 3.2.12 on 2023-03-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ngo_coverimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='img1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='img2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='img3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
