# Generated by Django 4.1.2 on 2023-04-07 06:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230318_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='coverimg',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
